server:
  port: 9999
  
   
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:lawyersdb}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:  
        ddl-auto: update
    hibernate:
      use-new-id-generator-mappings: false